name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller certifi

      - name: Build EXE
        run: |
          pyinstaller --noconfirm ^
            --onefile --windowed ^
            --name "RaspadorEmail" ^
            --collect-all bs4 ^
            --collect-all googlesearch ^
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RaspadorEmail_exe
          path: dist/RaspadorEmail.exe